### ISSUE TITLE
Test files for hands and objects challenges

### ISSUE THREAD

**Issue by mc-escobar11** [EGO4D/hands-and-objects#10]
Hi,
¿Where can I find the information of the test clips that are going to be used for evaluation in the PNR Temporal Localization and the Object State Change Classification challenges?

**Comment by abrhamkg** [comment]
In the downloaded dataset, there is a file called fho_oscc_pnr_test.json which contains all the information necessary to identify and use the test clips.

**Comment by mc-escobar11** [comment]
Thanks! found them
