### ISSUE TITLE
how to download test subset

### ISSUE THREAD

**Issue by idejie** [EGO4D/hands-and-objects#11]
I have downloaded the annotations.

But for the "Hand-Objects", there are only 'fho_xx_train.json' and 'fho_xx_val.json'.
How can I get the test split?

For example, the point-of-no-return temporal localization task needs a video clip for test. where are the clips for test and what is its u_id?

**Comment by Sid2697** [comment]
Hello @idejie! Thank you for reaching out.

As mentioned in https://github.com/EGO4D/hands-and-objects/issues/10, the test file is named as `fho_oscc_pnr_test.json` for the Object State Change Classification challenge. Other tasks have their corresponding test files (`fho_xx_test.json`). The files contain the information required to generate test clips along with their unique ids.

Regards,
Siddhant Bansal

**Comment by idejie** [comment]
Thanks, @Sid2697 !

I have downloaded all annotations by EGO4D-CLI.
```
python -m ego4d.cli.cli --output_directory="~/ego4d_data" --datasets annotations
```
 But, only `fho_xx_train.json` and `fho_xx_val.json`  were downloaded. `fho_xx_test.json` was not found. 

Are there errors I made? Or I don't have the permission of these `xx_test.json` files?

**Comment by Sid2697** [comment]
I see. @ebyrne can you please share your thoughts on this? Thanks!

**Comment by idejie** [comment]
Thanks, @Sid2697 @ebyrne ！
Can you provide these test files to me directly? like google drive?
