### ISSUE TITLE
Possible start code issues for Object state change classification task

### ISSUE THREAD

**Issue by FrankFcc** [EGO4D/hands-and-objects#14]
Thanks for sharing your wonderful work. However, I'm wondering if there are some issues Object state change classification task's starter code since it's currently disappeared. Can you take a glance at the task page if there are any issues encountered?

**Comment by Sid2697** [comment]
Hello @FrankFcc, thank you for reaching out.

Here is the link to the task page that I am able to access: https://github.com/EGO4D/hands-and-objects/tree/main/state-change-localization-classification

Can you please try this link and see if it works for you?

Regards,
Siddhant Bansal

**Comment by FrankFcc** [comment]
Hi @Sid2697 ,

Thanks for your reply and I've successfully reached the link. It seems that the link inside the task definition lead to a wrong address so I thought it didn't work. I thought you had better update the link in order to make it more clear. 

Best,
Changcheng

**Comment by Sid2697** [comment]
Hello @FrankFcc, 

Glad to know it worked for you. I checked a few places where we have linked to our repository and they all lead to the correct one. Can you please let me know from which webpage you got the broken link? Once I know, I will update the faulty link!

Regards,
Siddhant Bansal

**Comment by FrankFcc** [comment]
Hi @Sid2697,
Sure~ The wrong link is https://github.com/EGO4D/hands-and-objects/blob/main/object-of-change-detection/README.md which is under the main README.md and stay at third link([Object state change classification](https://github.com/EGO4D/hands-and-objects/blob/main/object-of-change-detection/README.md)) for the task definition section.

**Comment by Sid2697** [comment]
Thanks a lot @FrankFcc for pointing this out! We will fix the link.
