### ISSUE TITLE
The problem about batch size

### ISSUE THREAD

**Issue by mingxiaohuo** [EGO4D/hands-and-objects#18]
We run the Detr model, but the gpus are out of memory, we should reduce the batch size, but we haven't found the codes to change the batch size. However, we can only see an api about the batch size only in the ego4d environment. I want to ask if change the codes in the edo4d environment is the only method to change the batch size, thank you.

**Comment by Sid2697** [comment]
cc @fuqichen1998

**Comment by fuqichen1998** [comment]
You can modify [this line](https://github.com/EGO4D/hands-and-objects/blob/0aea0a4ed6ed1de4ffcb6b0cfa555da5c3c08bd7/state-change-object-detection-baselines/DETR/detr_256_6_6_torchvision_ego4dv1.yaml#L20) to easily adjust the batch size.
