### ISSUE TITLE
video ID 752dd54d-7835-475a-bccd-931fcf1e9655 has a 3 minute blank screen at the end

### ISSUE THREAD

**Issue by iranroman** [EGO4D/hands-and-objects#20]
Hello, 

I noticed that the video `752dd54d-7835-475a-bccd-931fcf1e9655` has a blank screen starting at the 11:23 timestamp. Is this on purpose, or do I have a corrupted file? 

Thanks!

**Comment by Sid2697** [comment]
Thanks @iranroman for reaching out! We already had a discussion about this on LinkedIn so closing the issue here. Feel free to re-open if you face the issue.

Regards,
Siddhant Bansal
