### ISSUE TITLE
Missmatch in annotation files

### ISSUE THREAD

**Issue by mc-escobar11** [EGO4D/hands-and-objects#3]
Hi, I’m working on the hands-objects interactions benchmark and I have a question. I’m trying to use the dataloader for the state change localization and classification task but it asks for some fields in the json file that I don’t have in fho_hands_[set].json or in fho_scod_[set].json.  For example, the dataloader expects the fields ‘state_change’,’parent_pnr_frame’, ‘unique_id’ but I couldn’t find them anywhere in the annotation files. Also, the dataloader uses the fields ‘parent_start_sec’, ‘parent_end_sec’, ‘parent_start_frame’ and ‘parent_end_frame’. The closest fields I could find where in fho_scod_[set].json  'clip_parent_start_sec', 'clip_parent_end_sec', 'clip_parent_start_frame', 'clip_parent_end_frame’. I was wondering if you could give me some insight on which is the correct annotation file I should be using. Thanks in advance!

**Comment by Sid2697** [comment]
Hello @mc-escobar11 ! Thank you for bringing the issue to our notice. I checked the files, and they are different. We are working on resolving this and will point you to the correct annotation files soon!

**Comment by ebyrne** [comment]
Thanks @mc-escobar11 , you want the files prefixed with `fho_oscc-pnr_` (e.g. `fho_oscc-pnr_train.json`).

There was a period where those were not being downloaded via the CLI (as they were updated), but they should be available now.  Can you please try pulling again with `--datasets annotations` and let us know if that matches with expectations?

Thanks for getting involved with Ego4D!  Let us know how it goes.

**Comment by mc-escobar11** [comment]
I checked and they are available now, thanks for the quick reply!

**Comment by ebyrne** [comment]
Ah, fantastic.  Sorry about the confusion then, that was an error on our side!

Do let us know how you get along with the dataset!
