### ISSUE TITLE
Error on line 16, detr_256_6_6_torchvision_ego4dv1.yaml, is something missing?

### ISSUE THREAD

**Issue by HimangiM** [EGO4D/hands-and-objects#9]
Looks like the detr_256_6_6_torchvision_ego4dv1.yaml has an error on line 16. Is the file missing something or is that a typo?

**Comment by Sid2697** [comment]
Hello @HimangiM, thank you for bringing this to our notice!

`DATASET:` entry there seems to be a typo as the next line has the same entry with other attributes. @fuqichen1998 can you please confirm once?

Thanks!

**Comment by fuqichen1998** [comment]
@HimangiM Thanks for spotting the typo. I have removed this extra line.
